import Link from "next/link";
import { Sparkles } from "lucide-react";
import { getTrees } from "@/lib/queries";
import { ACCENT_CLASSES } from "@/lib/theme";
import { Panel } from "@/components/Panel";
import { ProgressBar } from "@/components/ProgressBar";
import { DynamicIcon } from "@/components/DynamicIcon";

export default async function SkillTreesPage() {
  const trees = await getTrees();

  return (
    <>
      <header className="mb-7">
        <h1 className="font-display text-[22px] font-semibold tracking-wide md:text-[26px]">Skill Trees</h1>
        <p className="mt-2 max-w-2xl text-[13px] text-text-faint">
          Each node is a concrete capability. Complete quests linked to a node to earn its XP; finishing a node unlocks the ones built on it.
          Skills that need upkeep turn rusty if you stop practicing them.
        </p>
      </header>

      {trees.length === 0 ? (
        <Panel>
          <div className="flex flex-col items-start gap-3 text-[13px] text-text-dim">
            <Sparkles size={20} className="text-gold" />
            <p>
              No skill trees yet. Trees are generated by Claude: connect QuestOS to Claude, then ask something like{" "}
              <em className="text-text">&ldquo;Build me a skill tree for learning Spanish to conversational level.&rdquo;</em>
            </p>
            <Link href="/dashboard/settings" className="font-medium text-gold hover:underline">
              Set up the Claude connection
            </Link>
          </div>
        </Panel>
      ) : (
        <div className="grid grid-cols-1 gap-4 md:grid-cols-2 2xl:grid-cols-3">
          {trees.map((tree) => {
            const accent = ACCENT_CLASSES[tree.color];
            return (
              <Link
                key={tree.id}
                href={`/dashboard/skills/${tree.id}`}
                className={`group rounded-card border bg-panel p-5 transition-colors hover:bg-panel2 ${accent.border}`}
              >
                <div className="flex items-center gap-2.5">
                  <DynamicIcon name={tree.icon} size={18} strokeWidth={1.75} className={accent.text} />
                  <h2 className="font-display text-[15px] font-semibold tracking-wide">{tree.name}</h2>
                </div>
                {tree.description && <p className="mt-2 line-clamp-2 text-[12.5px] text-text-faint">{tree.description}</p>}
                <div className="mt-4">
                  <ProgressBar percent={tree.percent} barClassName={accent.bar} label={`${tree.name} progress`} />
                </div>
                <div className="mt-2 flex flex-wrap gap-x-4 font-mono text-[11px] text-text-faint">
                  <span>{tree.percent}%</span>
                  <span>
                    {tree.completeCount}/{tree.nodes.length} nodes
                  </span>
                  <span>{tree.nodes.filter((n) => n.state === "available").length} available</span>
                  {tree.rustyCount > 0 && <span className="text-orange">{tree.rustyCount} rusty</span>}
                </div>
              </Link>
            );
          })}
        </div>
      )}
    </>
  );
}
