import Link from "next/link";
import { Flame, TreeDeciduous, Sparkles, Swords, Zap, Hourglass } from "lucide-react";
import { Header } from "@/components/marketing/Header";
import { AnimatedHeadline } from "@/components/marketing/AnimatedHeadline";
import { PRIMARY_BUTTON_CLASS, SECONDARY_BUTTON_CLASS } from "@/lib/theme";

const FEATURES = [
  {
    icon: Flame,
    tint: "bg-orange-dim text-orange border-orange/30",
    title: "Quests & XP",
    body: "Log what you actually did today. Every quest completed earns XP toward your next level.",
  },
  {
    icon: TreeDeciduous,
    tint: "bg-green-dim text-green border-green/30",
    title: "Skill trees",
    body: "Skyrim-style trees for anything you want to learn. Finish a skill to unlock the ones built on it.",
  },
  {
    icon: Hourglass,
    tint: "bg-purple-dim text-purple border-purple/30",
    title: "Skills that stay sharp",
    body: "Skills you stop practicing turn rusty, so you know exactly what needs a refresher.",
  },
];

const STEPS = [
  { icon: Sparkles, title: "Describe a goal", body: "Tell Claude what you want to learn. It builds a custom skill tree in QuestOS." },
  { icon: Swords, title: "Clear daily quests", body: "Each quest trains a skill. Check it off and the XP lands on that node." },
  { icon: Zap, title: "Level up", body: "Unlock new skills, grow your streak, and watch your level climb." },
];

export default function HomePage() {
  return (
    <div className="flex w-full flex-1 flex-col">
      <Header />

      <main className="flex-1">
        <section className="relative overflow-hidden px-4 pb-20 pt-16 text-center sm:px-6 md:pt-24">
          <div aria-hidden className="pointer-events-none absolute left-1/2 top-0 h-[420px] w-[720px] -translate-x-1/2 rounded-full bg-gold/10 blur-3xl" />
          <span className="relative inline-flex items-center gap-1.5 rounded-full border border-gold/30 bg-gold/10 px-3 py-1 text-[12px] font-medium text-gold">
            <Sparkles size={13} /> Skill trees generated by Claude
          </span>
          <AnimatedHeadline
            text="Turn your daily life into an RPG."
            className="relative mx-auto mt-6 max-w-[760px] font-display text-[34px] font-semibold leading-[1.1] tracking-wide sm:text-[44px] md:text-[56px]"
          />
          <p className="relative mx-auto mt-5 max-w-[540px] text-[16px] leading-relaxed text-text-dim">
            Log quests, earn XP, and level up skill trees for anything you want to learn or keep sharp. One dashboard for
            the game you&apos;re actually playing.
          </p>
          <div className="relative mt-8 flex flex-wrap items-center justify-center gap-3">
            <Link href="/signup" className={`${PRIMARY_BUTTON_CLASS} px-6 py-3 text-[14.5px]`}>
              Start your first quest
            </Link>
            <Link href="/login" className={`${SECONDARY_BUTTON_CLASS} px-6 py-3 text-[14.5px]`}>
              Log in
            </Link>
          </div>
        </section>

        <section className="mx-auto grid w-full max-w-[1060px] gap-4 px-4 pb-16 sm:px-6 md:grid-cols-3">
          {FEATURES.map(({ icon: Icon, tint, title, body }) => (
            <div key={title} className="surface p-6">
              <span className={`mb-4 flex h-10 w-10 items-center justify-center rounded-[11px] border ${tint}`}>
                <Icon size={19} strokeWidth={2} aria-hidden />
              </span>
              <h2 className="mb-1.5 font-display text-[15px] font-semibold tracking-wide">{title}</h2>
              <p className="text-[13.5px] leading-relaxed text-text-dim">{body}</p>
            </div>
          ))}
        </section>

        <section className="mx-auto w-full max-w-[1060px] px-4 pb-20 sm:px-6">
          <h2 className="text-center font-display text-[22px] font-semibold tracking-wide md:text-[26px]">How it works</h2>
          <ol className="mt-8 grid gap-4 md:grid-cols-3">
            {STEPS.map(({ icon: Icon, title, body }, i) => (
              <li key={title} className="relative rounded-card border border-border/60 bg-panel/50 p-6">
                <span className="font-mono text-[12px] text-gold/80">0{i + 1}</span>
                <div className="mt-2 flex items-center gap-2">
                  <Icon size={16} className="text-gold" aria-hidden />
                  <h3 className="text-[15px] font-semibold">{title}</h3>
                </div>
                <p className="mt-2 text-[13.5px] leading-relaxed text-text-dim">{body}</p>
              </li>
            ))}
          </ol>
        </section>

        <section className="relative overflow-hidden border-t border-border/50 px-4 py-16 text-center sm:px-6">
          <div aria-hidden className="pointer-events-none absolute bottom-0 left-1/2 h-64 w-[600px] -translate-x-1/2 rounded-full bg-purple/10 blur-3xl" />
          <h2 className="relative font-display text-[24px] font-semibold tracking-wide">Ready to start your streak?</h2>
          <p className="relative mx-auto mt-2 max-w-[420px] text-[14px] text-text-dim">Free to use, single sign-up, your data stays yours.</p>
          <Link href="/signup" className={`${PRIMARY_BUTTON_CLASS} relative mt-6 inline-block px-6 py-3 text-[14.5px]`}>
            Create your account
          </Link>
        </section>
      </main>
    </div>
  );
}
