-- QuestOS migration 001: skill trees, XP ledger, MCP API tokens.
--
-- Run once in the Supabase SQL editor on a project that already has the
-- original schema. (supabase/schema.sql includes all of this for fresh
-- projects.) Safe to re-run: every statement is idempotent.

-- A user's skill tree (Coding, Guitar, Spanish, ...). Usually generated by
-- Claude over MCP, so `source` records where it came from.
create table if not exists skill_trees (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  description text not null default '',
  icon text not null default 'TreeDeciduous',
  color text not null default 'green' check (color in ('green', 'blue', 'purple', 'orange')),
  source text not null default 'manual' check (source in ('manual', 'mcp')),
  created_at timestamptz not null default now()
);
create index if not exists skill_trees_user_id_idx on skill_trees (user_id);

-- One perk/skill in a tree. `tier` is the node's depth (0 = root), derived
-- from its prerequisites when the tree is written. A node is complete once
-- its earned XP (from xp_events) reaches xp_required. `maintenance_days`
-- (optional) marks it "rusty" when not practiced for that many days.
create table if not exists skill_nodes (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  tree_id uuid not null references skill_trees(id) on delete cascade,
  name text not null,
  description text not null default '',
  icon text not null default 'Circle',
  xp_required int not null default 100 check (xp_required between 1 and 100000),
  tier int not null default 0 check (tier >= 0),
  position int not null default 0,
  maintenance_days int check (maintenance_days is null or maintenance_days between 1 and 365),
  created_at timestamptz not null default now()
);
create index if not exists skill_nodes_tree_id_idx on skill_nodes (tree_id);
create index if not exists skill_nodes_user_id_idx on skill_nodes (user_id);

-- Prerequisite edges: `node_id` unlocks once every `prereq_id` is complete.
create table if not exists skill_node_prereqs (
  node_id uuid not null references skill_nodes(id) on delete cascade,
  prereq_id uuid not null references skill_nodes(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  primary key (node_id, prereq_id),
  check (node_id <> prereq_id)
);
create index if not exists skill_node_prereqs_user_id_idx on skill_node_prereqs (user_id);

-- Quests can train a specific skill node.
alter table quests add column if not exists skill_node_id uuid references skill_nodes(id) on delete set null;

-- XP ledger: the single source of truth for level and skill progress.
-- Completing a quest inserts one row (quest_id set, unique); un-completing
-- or deleting the quest removes it. Activity logged over MCP has no quest.
create table if not exists xp_events (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  amount int not null check (amount between 1 and 10000),
  source text not null check (source in ('quest', 'mcp', 'manual')),
  quest_id uuid unique references quests(id) on delete cascade,
  skill_node_id uuid references skill_nodes(id) on delete set null,
  note text,
  created_at timestamptz not null default now()
);
create index if not exists xp_events_user_created_idx on xp_events (user_id, created_at);
create index if not exists xp_events_node_idx on xp_events (skill_node_id);

-- Personal access tokens for the MCP endpoint (/api/mcp). Only a SHA-256
-- hash is stored; the plain token is shown once when created.
create table if not exists api_tokens (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  token_hash text not null unique,
  created_at timestamptz not null default now(),
  last_used_at timestamptz
);
create index if not exists api_tokens_user_id_idx on api_tokens (user_id);

alter table skill_trees enable row level security;
alter table skill_nodes enable row level security;
alter table skill_node_prereqs enable row level security;
alter table xp_events enable row level security;
alter table api_tokens enable row level security;

-- Full CRUD on own rows. (The MCP endpoint uses the service-role key and
-- scopes every query by the token's user_id in application code.)
do $$
declare t text;
begin
  foreach t in array array['skill_trees', 'skill_nodes', 'skill_node_prereqs', 'xp_events'] loop
    execute format('drop policy if exists "own rows" on %I', t);
    execute format(
      'create policy "own rows" on %I for all using (auth.uid() = user_id) with check (auth.uid() = user_id)', t
    );
  end loop;
end $$;

-- Tokens: users can create, list and revoke their own. No update policy:
-- last_used_at is only written by the server with the service-role key.
drop policy if exists "select own api_tokens" on api_tokens;
drop policy if exists "insert own api_tokens" on api_tokens;
drop policy if exists "delete own api_tokens" on api_tokens;
create policy "select own api_tokens" on api_tokens for select using (auth.uid() = user_id);
create policy "insert own api_tokens" on api_tokens for insert with check (auth.uid() = user_id);
create policy "delete own api_tokens" on api_tokens for delete using (auth.uid() = user_id);

-- Backfill: quests completed before the ledger existed earn their XP, so
-- switching to ledger-derived levels doesn't reset anyone to level 1.
-- Idempotent via the unique quest_id.
insert into xp_events (user_id, amount, source, quest_id, skill_node_id, created_at)
select user_id, greatest(1, least(xp, 10000)), 'quest', id, skill_node_id, completed_at
from quests
where done and completed_at is not null
on conflict (quest_id) do nothing;

-- Aggregates run in Postgres, not by fetching rows: PostgREST caps plain
-- selects (1000 rows by default), which would silently truncate totals.
-- SECURITY INVOKER keeps RLS in force for signed-in callers, so passing
-- another user's id returns nothing; the service role (MCP) bypasses RLS
-- and relies on the id it resolved from the API token.

-- XP per skill node (skill_node_id null = XP not tied to a node).
create or replace function xp_summary(p_user_id uuid)
returns table (skill_node_id uuid, total bigint, last_at timestamptz)
language sql stable security invoker set search_path = public
as $$
  select skill_node_id, sum(amount)::bigint, max(created_at)
  from xp_events
  where user_id = p_user_id
  group by skill_node_id
$$;

-- Completed quests per UTC day since p_since, for the activity heatmap.
create or replace function activity_counts(p_user_id uuid, p_since timestamptz)
returns table (day date, completed bigint)
language sql stable security invoker set search_path = public
as $$
  select (completed_at at time zone 'utc')::date, count(*)::bigint
  from quests
  where user_id = p_user_id and done and completed_at >= p_since
  group by 1
$$;
